### PR TITLE
Added task entities to tes-adapter

### PR DESCRIPTION
**Pull request by evgeniimv**
added task entities in module as a result of swagger-codegen procedure.
command used to generate entities:
======================
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i samples/task_execution_swagger.json \
  -l spring \
  -o samples/tes-adapter
======================
As a result I had more than only task entities, but I implemented only last one.

### CODE REVIEW

**Comment by evgeniimv** [comment]
I need to do something with annotations in these entities, because after this addition I have a build failure - tes-adapter:pmdMain

**Comment by evgeniimv** [comment]
I managed cause of the problem. tes-adapter:pmdMain is the result of unused methods and fields in these new entities.

**Comment by evgeniimv** [comment]
suppose we should add one by one method and entity if we want to avoid this build failure)

**Comment by evgeniimv** [comment]
But some of these tasks connect with each other, so, seems we should implement whole set of methods to build it successfully without pmdMain trouble

**Review by mzueva — CHANGES_REQUESTED** [review]
Please fix for all generated code:
1. Add lombok `@Data` annotation to all entities and remove generated getters, setters, equals, hashCode and toString methods.
2. Move `ApiModelProperty ` from getters to fields, remove duplicated javadoc
2. Remove `Validates` and `@Generated` annotations

**Comment by evgeniimv** [comment]
fixed

**Review by mzueva — CHANGES_REQUESTED** [review]
I still see some generated methods in entities, at this point we do not need them.

**Comment by evgeniimv** [comment]
fixed

**Comment by evgeniimv** [comment]
I have a question about Enum classes, should I remove constructor or not? Just because it connects with enum parameters and if I will remove constructor I will forced to remove values for all enum-parameters also.

**Comment by mzueva** [comment]
> I have a question about Enum classes, should I remove constructor or not? Just because it connects with enum parameters and if I will remove constructor I will forced to remove values for all enum-parameters also.

@evgeniimv You can use `@AllArgsContructor` + `@Getter` on enumns

**Comment by evgeniimv** [comment]
fixed last issues. Removed constructors from enum-classes. Added @AllArgsConstructor and @ ToString annotations to them.

**Review by mzueva — APPROVED** [review]

**Pull request merged**
